create database zh_dwb;

create table zh_dwb.itcast_clue_dwb(
    id                          string,
    create_date_time            string comment '创建时间',
    update_date_time            string comment '最后更新时间',year_code string comment '年',
    month_code string comment '月',
    day_code string comment '日',
    hour_code string comment '小时',

    deleted                     string comment '是否被删除（禁用）',
    customer_id                 string comment '所属客户id',
    first_id                    string comment '第一条客户关系id',
    belonger                    string comment '归属人',
    belonger_name               string comment '归属人姓名',
    initial_belonger            string comment '初始归属人',
    distribution_handler        string comment '分配处理人',
    business_scrm_department_id string comment '归属部门',
    last_visit_time             string comment '最后回访时间',
    next_visit_time             string comment '下次回访时间',
    origin_type                 string comment '数据来源',
    itcast_school_id            string comment '校区Id',
    itcast_subject_id           string comment '学科Id',
    intention_study_type        string comment '意向学习方式',
    anticipat_signup_date       string comment '预计报名时间',
    level                       string comment '客户级别',
    creator                     string comment '创建人',
    current_creator             string comment '当前创建人：初始==创建人，当在公海拉回时为 拉回人',
    creator_name                string comment '创建者姓名',
    origin_channel              string comment '来源渠道',
    comment                     string,
    first_customer_clue_id      string comment '第一条线索id',
    last_customer_clue_id       string comment '最后一条线索id',
    process_state               string comment '处理状态',
    process_time                string comment '处理状态变动时间',
    payment_state               string comment '支付状态',
    payment_time                string comment '支付状态变动时间',
    signup_state                string comment '报名状态',
    signup_time                 string comment '报名时间',
    notice_state                string comment '通知状态',
    notice_time                 string comment '通知状态变动时间',
    lock_state                  string comment '锁定状态',
    lock_time                   string comment '锁定状态修改时间',
    itcast_clazz_id             string comment '所属ems班级id',
    itcast_clazz_time           string comment '报班时间',
    payment_url                 string comment '付款链接',
    payment_url_time            string comment '支付链接生成时间',
    ems_student_id              string comment 'ems的学生id',
    delete_reason               string comment '删除原因',
    deleter                     string comment '删除人',
    deleter_name                string comment '删除人姓名',
    delete_time                 string comment '删除时间',
    course_id                   string comment '课程ID',
    course_name                 string comment '课程名称',
    delete_comment              string comment '删除原因说明',
    close_state                 string comment '关闭装填',
    close_time                  string comment '关闭状态变动时间',
    appeal_id                   string comment '申诉id',
    tenant                      string comment '租户',
    total_fee                   string comment '报名费总金额',
    belonged                    string comment '小周期归属人',
    belonged_time               string comment '归属时间',
    belonger_time               string comment '归属时间',
    transfer                    string comment '转移人',
    transfer_time               string comment '转移时间',
    follow_type                 string comment '分配类型，0-自动分配，1-手动分配，2-自动转移，3-手动单个转移，4-手动批量转移，5-公海领取',
    transfer_bxg_oa_account     string comment '转移到博学谷归属人OA账号',
    transfer_bxg_belonger_name  string comment '转移到博学谷归属人OA姓名',
    customer_relationship_id    int comment '客户关系id',
    session_id                  string comment '七陌会话id',
    sid                         string comment '访客id',
    status                      string comment '状态（undeal待领取 deal 已领取 finish 已关闭 changePeer 已流转）',
    user_zx                     string comment '所属坐席',
    create_time                 string comment '七陌创建时间',
    platform                    string comment '平台来源 （pc-网站咨询|wap-wap咨询|sdk-app咨询|weixin-微信咨询）',
    s_name                      string comment '用户名称',
    seo_source                  string comment '搜索来源',
    seo_keywords                string comment '关键字',
    ip                          string comment 'IP地址',
    referrer                    string comment '上级来源页面',
    from_url                    string comment '会话来源页面',
    landing_page_url            string comment '访客着陆页面',
    url_title                   string comment '咨询页面title',
    to_peer                     string comment '所属技能组',
    manual_time                 string comment '人工开始时间',
    begin_time                  string comment '坐席领取时间 ',
    reply_msg_count             int comment '客服回复消息数',
    total_msg_count             int comment '消息总数',
    msg_count                   int comment '客户发送消息数',
    finish_reason               string comment '结束类型',
    finish_user                 string comment '结束坐席',
    end_time                    string comment '会话结束时间',
    platform_description        string comment '客户平台信息',
    browser_name                string comment '浏览器名称',
    os_info                     string comment '系统名称',
    area                        string comment '区域',
    country                     string comment '所在国家',
    province                    string comment '省',
    city                        string comment '城市',
    name                        string comment '客户姓名',
    idcard                      string comment '身份证号',
    phone                       string comment '手机号',
    itcast_school               string comment '校区',
    itcast_subject              string comment '学科',
    wechat                      string comment '微信',
    qq                          string comment 'qq号',
    email                       string comment '邮箱',
    gender                      string comment '性别',
    information_way             string comment '资讯方式',
    working_years               string comment '开始工作时间',
    technical_directions        string comment '技术方向',
    customer_state              string comment '当前客户状态',
    valid                       string comment '该线索是否是网资有效线索',
    clue_state                  string comment '线索状态',
    scrm_department_id          int comment 'SCRM内部部门id',
    superior_url                string comment '诸葛获取上级页面URL',
    superior_source             string comment '诸葛获取上级页面URL标题',
    landing_url                 string comment '诸葛获取着陆页面URL',
    landing_source              string comment '诸葛获取着陆页面URL来源',
    info_url                    string comment '诸葛获取留咨页URL',
    info_source                 string comment '诸葛获取留咨页URL标题',
    zhuge_session_id            string comment ' ',
    is_repeat                   int comment '是否重复线索(手机号维度) 0:正常 1：重复',
    activity_id                 string comment '活动id',
    activity_name               string comment '活动名称',
    shunt_mode_id               int comment '匹配到的技能组id',
    shunt_employee_group_id     int comment '所属分流员工组',
    customer_relationship_first_id string comment '第一条客户关系id',
    employee_id                    string comment '申诉人',
    employee_name                  string comment '申诉人姓名',
    employee_department_id         string comment '申诉人部门',
    employee_tdepart_id            string comment '申诉人所属部门',
    appeal_status                  string comment '申诉状态，0:待稽核 1:无效 2：有效',
    audit_id                       string comment '稽核人id',
    audit_name                     string comment '稽核人姓名',
    audit_department_id            string comment '稽核人所在部门',
    audit_department_name          string comment '稽核人部门名称',
    audit_date_time                string comment '稽核时间'
)
COMMENT '线索数据中间表'
row format delimited fields terminated by '\t'
stored as orc
tblproperties ('orc.compress' = 'SNAPPY');

drop table zh_dwb.itcast_clue_dwb;

insert overwrite table zh_dwb.itcast_clue_dwb
select
       cd.id                          ,
       cd.create_date_time            ,
       cd.update_date_time            ,
       substr(cd.create_date_time,1,4) as year_code,
       substr(cd.create_date_time,6,2) as month_code,
       substr(cd.create_date_time,9,2) as day_code,
       substr(cd.create_date_time,12,2) as hour_code,
       cd.deleted                     ,
       customer_id                 ,
       first_id                    ,
       belonger                    ,
       belonger_name               ,
       initial_belonger            ,
       distribution_handler        ,
       business_scrm_department_id ,
       last_visit_time             ,
       next_visit_time             ,
       origin_type                 ,
       itcast_school_id            ,
       itcast_subject_id           ,
       intention_study_type        ,
       anticipat_signup_date       ,
       level                       ,
       creator                     ,
       current_creator             ,
       creator_name                ,
       origin_channel              ,
       comment                     ,
       first_customer_clue_id      ,
       last_customer_clue_id       ,
       process_state               ,
       process_time                ,
       payment_state               ,
       payment_time                ,
       signup_state                ,
       signup_time                 ,
       notice_state                ,
       notice_time                 ,
       lock_state                  ,
       lock_time                   ,
       itcast_clazz_id             ,
       itcast_clazz_time           ,
       payment_url                 ,
       payment_url_time            ,
       ems_student_id              ,
       delete_reason               ,
       deleter                     ,
       deleter_name                ,
       delete_time                 ,
       course_id                   ,
       course_name                 ,
       delete_comment              ,
       close_state                 ,
       close_time                  ,
       appeal_id                   ,
       cd.tenant                      ,
       total_fee                   ,
       belonged                    ,
       belonged_time               ,
       belonger_time               ,
       transfer                    ,
       transfer_time               ,
       follow_type                 ,
       transfer_bxg_oa_account     ,
       transfer_bxg_belonger_name  ,
       customer_relationship_id    ,
       session_id                  ,
       sid                         ,
       status                      ,
       user_zx                     ,
       create_time                 ,
       platform                    ,
       s_name                      ,
       seo_source                  ,
       seo_keywords                ,
       ip                          ,
       referrer                    ,
       from_url                    ,
       landing_page_url            ,
       url_title                   ,
       to_peer                     ,
       manual_time                 ,
       begin_time                  ,
       reply_msg_count             ,
       total_msg_count             ,
       msg_count                   ,
       finish_reason               ,
       finish_user                 ,
       end_time                    ,
       platform_description        ,
       browser_name                ,
       os_info                     ,
       area                        ,
       country                     ,
       province                    ,
       city                        ,
       name                        ,
       idcard                      ,
       phone                       ,
       itcast_school               ,
       itcast_subject              ,
       wechat                      ,
       qq                          ,
       email                       ,
       gender                      ,
       information_way             ,
       working_years               ,
       technical_directions        ,
       customer_state              ,
       valid                       ,
       clue_state                  ,
       scrm_department_id          ,
       superior_url                ,
       superior_source             ,
       landing_url                 ,
       landing_source              ,
       info_url                    ,
       info_source                 ,
       zhuge_session_id            ,
       is_repeat                   ,
       activity_id                 ,
       activity_name               ,
       shunt_mode_id               ,
       shunt_employee_group_id     ,
       customer_relationship_first_id,  -- 投诉的人的id
       employee_id           ,
       employee_name         ,
       employee_department_id,
       employee_tdepart_id   ,
       appeal_status         ,
       audit_id              ,
       audit_name            ,
       audit_department_id   ,
       audit_department_name ,
       audit_date_time
from zh_dwd.itcast_clue_dwd cd left join zh_ods.scrm_customer_appeal ca  -- 投诉表，投诉成功的为无效线索
on cd.id=ca.customer_relationship_first_id;